const khu38data =
{
    'name':'Khu trọ 38',
    'floor':2,
    'rentalCosts':'2.5tr-7tr',
    'describe':'',
    'address':'38, đường 904',
    'province/city':'Thủ Đức',
    'district':'Phường Hiệp Phú',
    'open':'6am',
    'closed':'23am',
    'paymentDeadlineDate':5,
    'numberOfDaysNoticeBeforeMoving':15,
    'roomPaymentTime':[
        
    ],
    'buildingManager':[
        {
            'name':'Phạm Văn Hoàng',
            'phoneNumber':'0382823786',
            'avatarUrl':"https://tienganhdanang.edu.vn/wp-content/uploads/2023/06/anh-trai-dep-20023456-wap1022b252842529.jpg"
        } 
    ],
    'extraServicesFee-based':[

    ],

    'area':[
          {
            name: '01',
            'room code': '2H-01',
            expectedRoomPrice: '3m',
            floor: 0,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '02',
            'room code': '2H-02',
            expectedRoomPrice: '3m',
            floor: 0,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '03',
            'room code': '2H-03',
            expectedRoomPrice: '3m',
            floor: 0,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '04',
            'room code': '2H-04',
            expectedRoomPrice: '3m',
            floor: 0,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '05',
            'room code': '2H-05',
            expectedRoomPrice: '3m',
            floor: 0,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '06',
            'room code': '2H-06',
            expectedRoomPrice: '3m',
            floor: 0,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '101',
            'room code': '2H-101',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '102',
            'room code': '2H-102',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '103',
            'room code': '2H-103',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '104',
            'room code': '2H-104',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
        note: '',
            state: 'currently renting'
          },
          {
            name: '105',
            'room code': '2H-105',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '106',
            'room code': '2H-106',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '107',
            'room code': '2H-107',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '108',
            'room code': '2H-108',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '109',
            'room code': '2H-109',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '110',
            'room code': '2H-110',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '111',
            'room code': '2H-111',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '112',
            'room code': '2H-112',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '113',
            'room code': '2H-113',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '114',
            'room code': '2H-114',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '115',
            'room code': '2H-115',
            expectedRoomPrice: '3m',
            floor: 1,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '201',
            'room code': '2H-201',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '202',
            'room code': '2H-202',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '203',
            'room code': '2H-203',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '204',
            'room code': '2H-204',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '205',
            'room code': '2H-205',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '206',
            'room code': '2H-206',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '207',
            'room code': '2H-207',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'Expected blank'
          },
          {
            name: '208',
            'room code': '2H-208',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '209',
            'room code': '2H-209',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '210',
            'room code': '2H-210',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '211',
            'room code': '2H-211',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '212',
            'room code': '2H-212',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '213',
            'room code': '2H-213',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '214',
            'room code': '2H-214',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '215',
            'room code': '2H-215',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '216',
            'room code': '2H-216',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '217',
            'room code': '2H-217',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '218',
            'room code': '2H-218',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '219',
            'room code': '2H-219',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '220',
            'room code': '2H-220',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '221',
            'room code': '2H-221',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '222',
            'room code': '2H-222',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '223',
            'room code': '2H-223',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'Expected blank'
          },
          {
            name: '224',
            'room code': '2H-224',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '225',
            'room code': '2H-225',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '226',
            'room code': '2H-226',
            expectedRoomPrice: '3m',
            floor: 2,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '301',
            'room code': '2H-301',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '302',
            'room code': '2H-302',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '303',
            'room code': '2H-303',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '304',
            'room code': '2H-304',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '305',
            'room code': '2H-305',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '306',
            'room code': '2H-306',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '307',
            'room code': '2H-307',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '308',
            'room code': '2H-308',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '309',
            'room code': '2H-309',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '310',
            'room code': '2H-310',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '311',
            'room code': '2H-311',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '312',
            'room code': '2H-312',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '313',
            'room code': '2H-313',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '314',
            'room code': '2H-314',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '315',
            'room code': '2H-315',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '316',
            'room code': '2H-316',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '317',
            'room code': '2H-317',
            expectedRoomPrice: '3m',
            floor: 3,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '401',
            'room code': '2H-401',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '402',
            'room code': '2H-402',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '403',
            'room code': '2H-403',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '404',
         'room code': '2H-404',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '405',
            'room code': '2H-405',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '406',
            'room code': '2H-406',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '407',
            'room code': '2H-407',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '408',
            'room code': '2H-408',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '409',
            'room code': '2H-409',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '410',
            'room code': '2H-410',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '411',
            'room code': '2H-411',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '412',
            'room code': '2H-412',
            expectedRoomPrice: '3m',
        floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '413',
            'room code': '2H-413',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '414',
            'room code': '2H-414',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '415',
            'room code': '2H-415',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '416',
            'room code': '2H-416',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          },
          {
            name: '417',
            'room code': '2H-417',
            expectedRoomPrice: '3m',
            floor: 4,
            numberOfBedrooms: 1,
            numberOfLivingRooms: 1,
            acreage: 25,
            limitedNumberOfTenants: 4,
            deposit: '3m',
            service: '',
            pictures: [],
            roomAmenities: [],
            roomDescription: '',
            note: '',
            state: 'currently renting'
          }
        
        


    ]


}
export default khu38data;